using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AlarmClock : MonoBehaviour
{
    public AudioClip alarmSound; // Sound to play when the alarm is triggered
    public float noiseIncreaseAmount = 65.0f; // Amount of noise generated by hitting the alarm clock

    private AudioSource audioSource;
    private bool isAlarmActive = false;

    private NoiseMeterUI noiseMeterUI;

    private void Start()
    {
        audioSource = GetComponent<AudioSource>();
        noiseMeterUI = FindObjectOfType<NoiseMeterUI>();
        if (audioSource == null)
        {
            audioSource = gameObject.AddComponent<AudioSource>();
        }

        audioSource.clip = alarmSound;
        audioSource.loop = true;
        audioSource.playOnAwake = false;
    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            noiseMeterUI.SetNoiseLevel(noiseIncreaseAmount);
            StartCoroutine(TriggerAlarm());
        }
    }

    private IEnumerator TriggerAlarm()
    {
        if (!isAlarmActive && alarmSound != null)
        {
            isAlarmActive = true;
            audioSource.Play();
        }

        yield return new WaitForSeconds(audioSource.clip.length);

        if (isAlarmActive)
        {
            isAlarmActive = false;
            audioSource.Stop();
            noiseMeterUI.ResetNoiseLevel();
        }
    }
}