using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MusicBox : MonoBehaviour
{
    public SpriteRenderer spriteRenderer;
    public Sprite glowSprite;
    public float glowIntensity = 0.5f;

    private Sprite originalSprite;
    private Color originalColor;

    public PlayerController playerController;

    [Header("Canvas")]
    public KeyCode interactionKey = KeyCode.E;

    public GameObject interactionTextPrefab;
    private GameObject interactionTextInstance;

    public AudioSource musicBox; // Sound to play when the alarm is triggered
    [SerializeField] private bool isPlaying;

    private NoiseMeterUI noiseMeterUI;
    public AudioVolumeController audioController;
    public float noiseIncreaseAmount; // Amount of noise generated by hitting the alarm clock


    private void Start()
    {
        noiseMeterUI = FindObjectOfType<NoiseMeterUI>();

        originalSprite = spriteRenderer.sprite;
        originalColor = spriteRenderer.color;


        // Instantiate the interaction text as a child of the interactable object
        interactionTextInstance = Instantiate(interactionTextPrefab, transform);
        interactionTextInstance.SetActive(false); // Hide the interaction text initially
    }

    private void Update()
    {
        if (isPlaying)
        {
            noiseMeterUI.SetNoiseLevel(noiseIncreaseAmount);
        }

        if (isPlaying && audioController.game.activeInHierarchy)
        {
            musicBox.UnPause();
            isPlaying = true;
        }
        else
        {
            musicBox.Pause();
            isPlaying = false;
        }
    }

    private void OnTriggerStay2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            SetGlowEffect(true);

            if (Input.GetKeyDown(KeyCode.E) && !playerController.isJumping)
            {
                if (isPlaying)
                {
                    musicBox.Stop();
                    isPlaying = false;
                }
                else
                {
                    musicBox.Play();
                    isPlaying = true;
                }
            }

            interactionTextInstance.SetActive(true);
        }
    }

    private void OnTriggerExit2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            SetGlowEffect(false);

            interactionTextInstance.SetActive(false);
        }
    }

    private void SetGlowEffect(bool enabled)
    {
        if (enabled)
        {
            spriteRenderer.sprite = glowSprite;
            spriteRenderer.color = new Color(originalColor.r, originalColor.g, originalColor.b, glowIntensity);
        }
        else
        {
            spriteRenderer.sprite = originalSprite;
            spriteRenderer.color = originalColor;
        }
    }
}
